# Pytorch Basic Operations
The **Tensor** is a fundamental structure in PyTorch which is very similar to an array or matrix. Tensors are used to encode the inputs and outputs of a model, as well as the model’s parameters. In this exercise, you will learn how to implement basic tensor operations.

In [1]:
"""
ONLY COMPLETE METHODS AND CLASSES MARKED "TODO".
DO NOT IMPORT ADDITIONAL LIBRARIES.
"""
import torch

For some of the exercises, the documentation of `torch.Tensor` should be very helpful:
https://pytorch.org/docs/stable/tensors.html

Basically, when you see an unfamiliar function, you should check in the documentation to see what the **input/output** of the function should look like, what **parameters** are needed and how these parameters will affect the result.

# Create Tensors

In [2]:
# Create tensors
shape = (2, 3,)
x = torch.rand(shape)
y = torch.rand(shape)
z = torch.zeros(shape)

# Addition
Implement a simple tensor addition x + y and assign the result to z.

In [3]:
"""
TODO: Implement a simple tensor addition x + y.
Assign the result to z.
"""
z = torch.add(x, y)

print("x = :")
print(x)
print("y = :")
print(y)

print("\n")

print("x + y = :")
print(z)
print("\n")

x = :
tensor([[0.4571, 0.5647, 0.5417],
        [0.7305, 0.3078, 0.3100]])
y = :
tensor([[0.9108, 0.2358, 0.4462],
        [0.9321, 0.8761, 0.7162]])


x + y = :
tensor([[1.3679, 0.8006, 0.9879],
        [1.6625, 1.1839, 1.0261]])




## Reshape
Reshape the tensor **z** into the specified shape (new_shape)

In [4]:
z = torch.rand([2, 3])
new_shape = (3, 2)

"""
TODO: Reshapes the tensor z with the given shape (new_shape)
Hint: use view()
"""
z = z.view(new_shape)

print("z and its shape after reshaping:")
print(z)
print(z.shape)
print("\n")

z and its shape after reshaping:
tensor([[0.1853, 0.5492],
        [0.5001, 0.7611],
        [0.2111, 0.1555]])
torch.Size([3, 2])




## Flatten
Flatten the tensor **z**.

In [5]:
z = torch.rand([2,3])
"""
Flatten
TODO: Flatten the tensor z.
Hint: use view()
"""

z = z.view(-1)

# you can also use z = torch.flatten(z) in case z is not contiguous.

print("z and its shape after the flatten operation:")
print(z)
print(z.shape)
print("\n")

z and its shape after the flatten operation:
tensor([0.1918, 0.1626, 0.9530, 0.0463, 0.2907, 0.1947])
torch.Size([6])




## Transpose
Swap the first dimension and the second dimension of **z**.

In [6]:
z = torch.rand([2,3])

"""
TODO: Swaps the first dimension and the second dimension of z.
"""
z = torch.transpose(z, 0, 1)


print("z and its shape after the transpose operation:")
print(z)
print(z.shape)
print("\n")

z and its shape after the transpose operation:
tensor([[0.3418, 0.6719],
        [0.6707, 0.9390],
        [0.9998, 0.4327]])
torch.Size([3, 2])




## Permutation
Permute the dimensions of **z** according to the specified order (exchanging axes).

In [7]:
"""
Permutation
TODO: Permute the dimensions of z according to the given order (swapping axes).
"""

# Create a new tensor
shape = (3,5,1)
z = torch.rand(shape)
order = [2,0,1]

z = z.permute(order)

print("z and its shape after permutation")
print(z)
print(z.shape)
print("\n")

z and its shape after permutation
tensor([[[0.9886, 0.6201, 0.6388, 0.6588, 0.1150],
         [0.6969, 0.2699, 0.7233, 0.0247, 0.7326],
         [0.1679, 0.1228, 0.7694, 0.5923, 0.9712]]])
torch.Size([1, 3, 5])




## Dot Product
Calculate the dot product of two rank 1 tensors (vectors) u and v.

In [8]:
"""
TODO: Calculate the dot product of
      two rank 1 tensors (vectors) u and v.
"""

# Create two vectors
v = torch.tensor([2, 3])
u = torch.tensor([2, 1])

result = torch.dot(u, v)

print("The dot product of u and v:")
print(result.item())
print("\n")

The dot product of u and v:
7




## Concatenation

In [9]:
shape = (2,3,)
x = torch.rand(shape)
y = torch.rand(shape)

"""
TODO: Concatenate (x,y) in dimension 1.
"""
z = torch.cat((x, y), dim=1)

print("The Concatenated tensor z of (x, y)")
print(z)
print("\n")

The Concatenated tensor z of (x, y)
tensor([[0.4912, 0.8874, 0.7180, 0.7024, 0.7580, 0.3244],
        [0.5229, 0.2775, 0.7153, 0.2166, 0.1956, 0.5835]])


