# Pytorch Basic Operations
The **Tensor** is a fundamental structure in PyTorch which is very similar to an array or matrix. Tensors are used to encode the inputs and outputs of a model, as well as the model’s parameters. In this exercise, you will learn how to implement basic tensor operations.

In [1]:
"""
ONLY COMPLETE METHODS AND CLASSES MARKED "TODO".
DO NOT IMPORT ADDITIONAL LIBRARIES.
"""
import torch

For some of the exercises, the documentation of `torch.Tensor` should be very helpful:
https://pytorch.org/docs/stable/tensors.html

Basically, when you see an unfamiliar function, you should check in the documentation to see what the **input/output** of the function should look like, what **parameters** are needed and how these parameters will affect the result.

# Create Tensors

In [2]:
# Create tensors
shape = (2, 3,)
x = torch.rand(shape)
y = torch.rand(shape)
z = torch.zeros(shape)

# Addition
Implement a simple tensor addition x + y and assign the result to z.

In [3]:
"""
TODO: Implement a simple tensor addition x + y.
Assign the result to z.
"""
z = torch.add(x, y)

print("x = :")
print(x)
print("y = :")
print(y)

print("\n")

print("x + y = :")
print(z)
print("\n")

x = :
tensor([[0.2192, 0.1668, 0.8247],
        [0.0848, 0.9460, 0.2757]])
y = :
tensor([[0.0108, 0.4095, 0.1484],
        [0.5477, 0.0467, 0.9697]])


x + y = :
tensor([[0.2300, 0.5763, 0.9731],
        [0.6325, 0.9927, 1.2454]])




## Reshape
Reshape the tensor **z** into the specified shape (new_shape)

In [4]:
z = torch.rand([2, 3])
new_shape = (3, 2)

"""
TODO: Reshapes the tensor z with the given shape (new_shape)
Hint: use view()
"""
z = z.view(new_shape)

print("z and its shape after reshaping:")
print(z)
print(z.shape)
print("\n")

z and its shape after reshaping:
tensor([[0.3857, 0.9370],
        [0.1971, 0.7429],
        [0.0452, 0.4709]])
torch.Size([3, 2])




## Flatten
Flatten the tensor **z**.

In [5]:
z = torch.rand([2,3])
"""
Flatten
TODO: Flatten the tensor z.
Hint: use view()
"""

z = z.view(-1)

# you can also use z = torch.flatten(z) in case z is not contiguous.

print("z and its shape after the flatten operation:")
print(z)
print(z.shape)
print("\n")

z and its shape after the flatten operation:
tensor([0.5940, 0.4378, 0.1715, 0.4109, 0.9393, 0.6677])
torch.Size([6])




## Transpose
Swap the first dimension and the second dimension of **z**.

In [6]:
z = torch.rand([2,3])

"""
TODO: Swaps the first dimension and the second dimension of z.
"""
z = torch.transpose(z, 0, 1)


print("z and its shape after the transpose operation:")
print(z)
print(z.shape)
print("\n")

z and its shape after the transpose operation:
tensor([[0.0395, 0.0163],
        [0.6335, 0.1238],
        [0.4779, 0.9535]])
torch.Size([3, 2])




## Permutation
Permute the dimensions of **z** according to the specified order (exchanging axes).

In [7]:
"""
Permutation
TODO: Permute the dimensions of z according to the given order (swapping axes).
"""

# Create a new tensor
shape = (3,5,1)
z = torch.rand(shape)
order = [2,0,1]

z = z.permute(order)

print("z and its shape after permutation")
print(z)
print(z.shape)
print("\n")

z and its shape after permutation


## Dot Product
Calculate the dot product of two rank 1 tensors (vectors) u and v.

In [8]:
"""
TODO: Calculate the dot product of
      two rank 1 tensors (vectors) u and v.
"""

# Create two vectors
v = torch.tensor([2, 3])
u = torch.tensor([2, 1])

result = torch.dot(u, v)

print("The dot product of u and v:")
print(result.item())
print("\n")

The dot product of u and v:
7




## Concatenation

In [9]:
shape = (2,3,)
x = torch.rand(shape)
y = torch.rand(shape)

"""
TODO: Concatenate (x,y) in dimension 1.
"""
z = torch.cat((x, y), dim=1)

print("The Concatenated tensor z of (x, y)")
print(z)
print("\n")

The Concatenated tensor z of (x, y)
tensor([[0.1891, 0.1467, 0.1021, 0.5837, 0.3533, 0.1094],
        [0.0145, 0.7058, 0.3606, 0.3264, 0.7732, 0.5447]])


