# torch.Tensor
A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.

### Data Types
Torch defines 10 tensor types with CPU and GPU variants which are as follows:

### Initializing and basic operations
A tensor can be constructed from a Python `list` or sequence using the `torch.tensor()` constructor:

In [1]:
import torch
import numpy as np

In [2]:
torch.tensor([[1., -1.], [1., -1.]])
torch.tensor(np.array([[1, 2, 3], [4, 5, 6]]))

tensor([[1, 2, 3],
        [4, 5, 6]])

# Warning!
`torch.tensor()` always copies data. If you have a Tensor data and just want to change its `requires_grad` flag, use `requires_grad_()` or `detach()` to avoid a copy. If you have a numpy array and want to avoid a copy, use `torch.as_tensor()`.

A tensor of specific data type can be constructed by passing a `torch.dtype` and/or a `torch.device` to a constructor or tensor creation op:

In [3]:
torch.zeros([2, 4], dtype=torch.int32)
cuda0 = torch.device('cuda:0')
torch.ones([2, 4], dtype=torch.float64, device=cuda0)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0', dtype=torch.float64)

For more information about building Tensors, see Creation Ops (https://pytorch.org/docs/stable/torch.html#tensor-creation-ops)

The contents of a tensor can be accessed and modified using Python’s indexing and slicing notation:

In [4]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x[1][2])
x[0][1] = 8
print(x)

tensor(6)
tensor([[1, 8, 3],
        [4, 5, 6]])


Use `torch.Tensor.item()` to get a Python number from a tensor containing a single value:

In [5]:
x = torch.tensor([[1]])
x

tensor([[1]])

In [6]:
x = torch.tensor(2.5)
x

tensor(2.5000)

In [7]:
x.item()

2.5

For more information about indexing, see Indexing, Slicing, Joining, Mutating Ops (https://pytorch.org/docs/stable/torch.html#indexing-slicing-joining)

A tensor can be created with requires_grad=True so that torch.autograd records operations on them for automatic differentiation.

In [8]:
x = torch.tensor([[1., -1.], [1., 1.]], requires_grad=True)
out = x.pow(2).sum()
out.backward()
x.grad

tensor([[ 2., -2.],
        [ 2.,  2.]])

Each tensor has an associated `torch.Storage`, which holds its data. The tensor class also provides multi-dimensional, strided (https://en.wikipedia.org/wiki/Stride_of_an_array) view of a storage and defines numeric operations on it.

- For more information on tensor views, see Tensor Views. (https://pytorch.org/docs/stable/tensor_view.html#tensor-view-doc)
- For more information on the `torch.dtype`, `torch.device`, and `torch.layout` attributes of a `torch.Tensor`, see Tensor Attributes (https://pytorch.org/docs/stable/tensor_attributes.html#tensor-attributes-doc).
- Methods which mutate a tensor are marked with an underscore suffix. For example, `torch.FloatTensor.abs_()` computes the absolute value in-place and returns the modified tensor, while `torch.FloatTensor.abs()` computes the result in a new tensor.
- To change an existing tensor’s `torch.device` and/or `torch.dtype`, consider using `to()` method on the tensor.
- warning: Current implementation of `torch.Tensor` introduces memory overhead, thus it might lead to unexpectedly high memory usage in the applications with many tiny tensors. If this is your case, consider using one large structure.